name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Prepare test environment
        run: mkdir files && chmod +x ./mvnw
      - name: Build and test
        run: ./mvnw clean package

      - name: Check test results
        run: |
          if [ "$?" -ne 0 ]; then
            echo "Tests failed. Rejecting PR or commit."
            exit 1
          fi
