version: "0.0.1"
services:
  file:
    build:
      context: ..
      dockerfile: Dockerfile
    image: file-service
    container_name: file-service
    ports:
      - "8080:8080"
    volumes:
      - ./files:/app/files
    environment:
      JAVA_OPTS_RUN: "-Xms1g -Xmx4g"